### PR TITLE
remove version requirements on coverage so tests pass again

### PR DESCRIPTION
**Pull request by jordanrinke**
remove version requirements on coverage, tests pass with latest version and mix versions cause combine to fail, which causes report to fail.

### CODE REVIEW

**Comment by GMLudo** [comment]
This PR doesn't seem to improve the situation ;-)
No time for now to help you right now :-/

**Comment by jordanrinke** [comment]
No worries, I am working it out - it is an issue in travis now. It will take me a few attempts to get it, Just ignore this PR until it is passing ;)

**Comment by jordanrinke** [comment]
Almost there, just need to fix the flake8 bit now

**Comment by jordanrinke** [comment]
There we go, this should also fix your coveralls reporting now too.

**Comment by GMLudo** [comment]
Ok, it seems to be OK, we will see. 

Thanks a lot for your time. 

Have a nice day.

**Pull request merged**
