### PR TITLE
Middleware support

### PR DESCRIPTION
**Pull request by Ovvovy**

### CODE REVIEW

**Comment by GMLudo** [comment]
Hi @gawel,

This is a feature we're using in our fork of Panoramisk internally, it's like middlewares in Django or aiohttp.web for FastAGI.
We use that for example to maintain an SQL transaction for the all FastAGI endpoints.

It's implemented and tested, but not yet documented, @Ovvovy will do that soon.

Ok for you or you have some remarks ?

Happy new yeatr

**Comment by gawel** [comment]
I find it weird to wrap each route instead of a single entry point but I guess you don't have a choice

**Comment by GMLudo** [comment]
> I find it weird to wrap each route instead of a single entry point but I guess you don't have a choice

Come on, you have always the choice ;-)
This PR implements the strict middleware definition you have in Django and aiohttp.web

However, we have a sub-class where we have a small addon to add configuration for middlewares and customize the behaviour of the middleware by endpoint.

For example, it enables us to have aiopg transaction enabled or not for a specific endpoint:

    router.add_route('call_forwards/change', call_forwards.change, env_config=['aiopg'])

In fact, we have +15 000 lines of code for one application where we use Panoramisk inside, and we use these features heavily to avoid to repeat ourselves in FastAGI endpoints.
We propose this PR, because, when you have a big application, it's useful, at least to us.

For me, this pull request is more a gift for Panoramisk community than a mandatory feature I must have in Panoramisk.

As you like @gawel, we can continue to sub-class panoramisk for everything, only for our environment mechanism, or have everything in panoramisk and don't sub-class anymore.

Don't forget you're the BDFL of Panoramisk ;-)

Let me know your decision.

**Comment by gawel** [comment]
Can't this be done with decorators ?

Also it's weird that middlewares and routes don't have the same signature

**Comment by GMLudo** [comment]
> Can't this be done with decorators ?

It can as with context managers, but it means you need to add that for each endpoint.

> Also it's weird that middlewares and routes don't have the same signature

It isn't possible for the factory, to have an access to application.

**Comment by gawel** [comment]
> > Can't this be done with decorators ?
> 
> It can as with context managers, but it means you need to add that for each endpoint.
> 

Well you have to define your env_config for each endpoint too

> > Also it's weird that middlewares and routes don't have the same signature
> 
> It isn't possible for the factory, to have an access to application.

This don't really explain why they don't have the same api

Why is it necessary for the middleware but not for the original route?

If you need the app then you can either:

- add it as a request attribute

- use an app method as middleware

**Comment by GMLudo** [comment]
> Why is it necessary for the middleware but not for the original route?

Yes, it's technically possible to do in another way.
In fact, it's to have the same behaviour as aiohttp.web: http://aiohttp.readthedocs.io/en/stable/web.html#aiohttp-web-middlewares

Nevermind, I close this pull request.

**Comment by gawel** [comment]
I really don't understand this choice... I miss WSGI specs so much...

**Pull request closed without merging**
