### PR TITLE
Improve automatic reconnections

### PR DESCRIPTION
**Pull request by GMLudo**
Hi,

This pull request tries to improve automatic reconnections in Panoramisk.
Now, a new config parameter `automatic_reconnection` permits to choose the behaviour wanted with Panoramisk.
When this parameter is False, then the future of an action launched returns a `DisconnectedError` Exception. Before, you didn't know via the future that your action has failed.
When `automatic_reconnection` is True, all broken actions are queued until a stable connection is available again.

Thanks for your feedbacks.

PS: For now, the automatic tests in this PR are broken.
If everybody is happy with this PR, I'll fix tests before merge.
If somebody else wants to help me to fix the tests, be my guest.

### CODE REVIEW

**Comment by gawel** [comment]
I like to avoid custom exceptions. Can't you just use OSError/IOError instead of DisconnectError ?

**Comment by GMLudo** [comment]
@gawel: I've taken the inspiration from aiohttp: https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/errors.py

I've made a custom error also because I need to track that's the action that is broken by the DisconnectError: https://github.com/gawel/panoramisk/pull/31/files#diff-47109416e2b4891c524212335aeb66c9R149

However, I should change the parent class of DisconnectError, to use a more specific Exception.
An idea of Exception I could use ?

**Comment by gawel** [comment]
You can at least use the ConnectionResetError:

```
>>> ConnectionResetError
<class 'ConnectionResetError'>
```

Custom exceptions sucks, even if aiohttp use them

**Comment by GMLudo** [comment]
BrokenPipeError should match better this error: https://docs.python.org/3/library/exceptions.html#BrokenPipeError

Ok to you ?

**Comment by gawel** [comment]
As long as it's builtin it's ok

**Comment by gawel** [comment]
Don't know what to do with that... Still broken after merging with master.

**Comment by GMLudo** [comment]
I need time to adapt tests suite.
I'll do that as soon as possible.

**Comment by GMLudo** [comment]
Not necessary anymore with #43

**Pull request closed without merging**
