### PR TITLE
Originate async fix

### PR DESCRIPTION
**Pull request by litnimax**
There is a bug in Originate async - condition error.
send_action with Originate with ``async=true``  did not return as it is expected and waited until OriginateResponse event was generated to return it in list.
Here is the fix.

### CODE REVIEW

**Comment by gawel** [comment]
looks like this break all the tests https://travis-ci.org/github/gawel/panoramisk/builds/700853110

**Comment by litnimax** [comment]
> looks like this break all the tests https://travis-ci.org/github/gawel/panoramisk/builds/700853110

How can it be when my branch is just forked from yours? :-)
So it is not my commit that breaks the test is your test does not work :-)

**Comment by romkazor** [comment]
Confirm topic prodblem

> looks like this break all the tests https://travis-ci.org/github/gawel/panoramisk/builds/700853110

Your test only for Origiante with option async: false, but more preferably option async: true

**Comment by litnimax** [comment]
@gawel your idea to return OriginateResponse as action reply is fine.
But it breaks the asynchronous model of placing many calls from one manager conneciton.

**Comment by gawel** [comment]
The build is made for your PR so yes, you're commit break the tests. Don't know where it as to be fixed (code / test) but there's a problem.

**Comment by litnimax** [comment]
> The build is made for your PR so yes, you're commit break the tests. Don't know where it as to be fixed (code / test) but there's a problem.

But do u see this little change? So I think the problem is with test :-)

**Comment by gawel** [comment]
Maybe. Just need a PR with no broken things here.

**Comment by litnimax** [comment]
Ok. Digging into your code I understand why the test failed.
Let discuss the problem and the solution.
Some AMI actions like QueueStatus, QueueSummary, etc return many messages as events.
Your library tries to catch them all and return as a result of send_action operation.
The same you did with Originate.
By my opinion this is not the case like with QueueSummary and other multi-message actions.
All these multi-message actions generate an immediate list of messages that are fired as events.
The only action that is not immediate is Originate (do u know other?).
Asterisk developers created 2 modes of Origination
1) Sync when socket is not sent back the result until the 1-st leg origination returns.
2) Async when socket is sent back the result immediately with message that origination was queued. 
So the 2-nd option was created to use one socket connection to send many origination requests at one time without blocking.

Now about Panoramisk design. You decided to apply the same multi-message design as your applied for QueueSummary and others. But my opinion this is not correct.
As this breaks async design of originate as in both cases send_action will return only if
1) sync originate returnes
2) async originate will get OriginateResponse message.
So in both cases send_action is blocked.
So my proposal is just to remove Originate from multi-message actions what I did in the latest commit.
Or what is the sense in sending async=true while it is not actually async?

**Comment by litnimax** [comment]
The test did not rebuild after the 2-nd commit.
So I am closing this PR and open a new one.

**Comment by gawel** [comment]
The test was rebuild. See https://travis-ci.org/github/gawel/panoramisk/builds/701049878
It seems travis do not send feedback to github anymore.

Thanks for the effort. You have to keep in mind that I'm not an asterisk guru and I'm totally open to discussion.

Did you see the call_manager here ? https://github.com/gawel/panoramisk/blob/master/panoramisk/call_manager.py

It uses Originate with async=true. It track the call and you'll get a response when it's ended.

I think that there is a misunderstanding because asyncio is not async in asterisk. What you seems to call "blocking" is "block until you'll get all originate responses". But nothing is really blocked in panoramisk because of asyncio.

To me it looks like you need to get some feedback before the call ends with async=true. And yes, panoramisk does not allow that. 

What would be awesome is to use an async iterator. something like:

```
async for response in send_action(..., iterate=True):
    # you'll get feed back at each steps
```

`async for` is "new". panoramisk was built before it exists

It may be a harder task than just removing 2 lines of code to feet your needs ;)

**Pull request closed without merging**
