### PR TITLE
Improve AGI errors handling

### PR DESCRIPTION
**Pull request by areski**
I ran few testing and met few issues with the fastAGI Panoramisk implementation. Most of the issues were related of the strong contract with the AGI command. Here it's an approach to loose sightly this contract and ensure we can build more complex fastAGI application.

The PR fix also the send_command "GET DATA", and therefore will allow one to build basic IVR application.

The exception file is not used, but I left it here for discussion in case we prefer to handle errors by throwing exceptions rather than returning error code, I don't have previous experience with asyncio, so I don't know if working with exception is rather a bad idea which was my impression.

FYI, at a later stage, I would like to implement all the AGI commands and add a test suits for them.

cc @GMLudo

### CODE REVIEW

**Comment by GMLudo** [comment]
Hi @areski,

First, thanks a lot about your time, it's better than I can dreamed ;-)

In your PR, I see three things:
1. You want to write complex FastAGI applications: I can understand that, I've used safi during a long time with the same approach. From my experience, I prefer to write most of dialplan as possible and use FastAGI only if necessary: You increase the efficiency of the system, at least based on my measures with sipp. However, I see no problem to write a complex FastAGI application, it's also a concrete valid use case, it's easier for a Python developer to write everything in Python, like with ORM and SQL.
2. With this complex FastAGI application approach, you spot bugs: I'm agree with you, need to fix.
3. You want also to imitate starpy API where each AMI or AGI command is a python method. To be really honest with you, if I selected Panoramisk to replace starpy is because you have a very small layer between AMI/FastAGI and Python: The developer is more autonomous, easier to debug and better efficiency (less lines of code). Moreover, you must start to follow AMI version during login to adapt your Python API.
From my point of view: a lot of work for the maintainers with few added value for the end-dev: Ok, he will have autocompletion, however, he needs to continue to read Asterisk documentation to understand his job.
That's said, I don't see a big issue to have a higher Python API, if only we keep the actual API **and** you maintain your higher Python API ;-)

For exceptions, I need to sleep on that: I'm not always sure where to place the cursor when you have a high-level error.

First, if you could redo the PR with only bugfixes and the complex IVR example, I'll merge that.

BTW, I must fix travis-ci error, I'll try to do that tomorrow.

**Comment by areski** [comment]
Thanks for the feedback @GMLudo 

1) I totally agree on the what you are mentioning about performance but there is a need for some developers to build their logic in Python. I can give examples if needed but I'm sure you know of all of it already :)

2) Cool

3) Ideally yes, so that we don't have to write code like "yield from request.send_command('GET DATA hello-world 5000 2')" but rather have an clean API around it.I brought this here to discuss about it and see if there is some interest for that in Panoramisk, this can be build as an external module too if we dont want this in the codebase.

I removed the exceptions, the rest of the PR is focused on the problem to solve. 

I'm on IRC Freenode - areski, if need to clarify something.

**Comment by GMLudo** [comment]
3) Clean API is a point of view: From my point of view "yield from request.send_command('GET DATA hello-world 5000 2')" is cleaner because is 1-to-1 command with the Asterisk documentation content ;-)

4) I don't see a commit to remove that. For Exceptions, I've discussed internally here, we are agree with you for syntax error and cie. However, I prefer a separate pull request for this point.

5) I've no problems to discuss by IRC, however, for architecture decisions, I prefer on Github to keep a more visible trace: Easier to avoid the same discussions for newcomers.

**Comment by areski** [comment]
AGI Exceptions is removed here https://github.com/areski/panoramisk/commit/a3c161194548418ccad803c3cf43c9cdf2006e9e

**Comment by GMLudo** [comment]
Very strange, you find a bug in github ;-)

**Comment by areski** [comment]
I can see it clearly in this view, plus it shows as well in "Commits" / "Files changed" section

**Comment by GMLudo** [comment]
Very strange, it's ok now.

I've merged, thanks again.

**Comment by areski** [comment]
Thanks!

**Pull request merged**
