### PR TITLE
event listener outputs all asterisk events to the screen

### PR DESCRIPTION
**Pull request by tannermkerr**
For current open issue

### CODE REVIEW

**Comment by GMLudo** [comment]
Hi,

I'm not sure to understand why you have `queue_status` function ? What's the goal ?
You have some failed checks in travis-ci: https://travis-ci.org/gawel/panoramisk/builds/86917231

BTW, thanks a lot to contribute in examples ;-)

Have a nice day.

**Comment by tannermkerr** [comment]
Sorry, that's an error on my part we were in the middle of building something else when we created that example I've pushed the update. That function should be called keep_alive() not queue_status().

Also, We don't know how to fix code coverage errors for an example.

**Comment by GMLudo** [comment]
To me, this coroutine is useless.
You can keep up and running your daemon with `run_forever()` method.

Look in aiohttp example:
https://github.com/KeepSafe/aiohttp/blob/master/examples/web_srv.py#L61

**Comment by tannermkerr** [comment]
Thanks for that great example @GMLudo. We'll look into why that travis-ci is failing this weekend.

**Comment by GMLudo** [comment]
The easiest is flake8: https://travis-ci.org/gawel/panoramisk/jobs/87145546
For others, I don't know: don't hesitate to launch the same command on your dev instance.

**Comment by jordanrinke** [comment]
@tannermkerr tests have been fixed, you should pull master and refresh with your run_forever() changes for a clean commit/PR

**Comment by GMLudo** [comment]
Thanks.

**Pull request merged**
